spring:
  security:
    oauth2:
      client:
        registration:
          fitbit:
            provider: fitbit
            client-id: ${clientId}
            client-secret: ${clientSecret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - activity
              - heartrate
              - location
              - nutrition
              - profile
              - settings
              - sleep
              - social
              - weight
        provider:
          fitbit:
            authorization-uri: https://www.fitbit.com/oauth2/authorize
            token-uri: https://api.fitbit.com/oauth2/token
            user-info-uri: https://api.fitbit.com/1/user/-/profile.json
            user-name-attribute: encodedId

fitbit:
  api:
    base-url: https://api.fitbit.com

access:
  logging:
    path: ${ACCESS_LOG_PATH:/tmp/gakuseki.txt}

ngrok:
  command: "http --region=jp 8080"
  enabled: false
  auth-token:

server:
  forward-headers-strategy: framework
