fitbit:
  api:
    clientId: # Here's your id
    clientSecret: # Here's your code
    callbackURL: # Here's your url
access:
  logging:
    path: /tmp/gakuseki.
ngrok:
  command: http -region=jp --subdomain=mcom 8080
  enabled: false
  auth-token: # Here's your token